name: unique-name
stage: ${opt:stage, dev}
client: ${opt:client, connect}
database:
  host: 'local-bituhh.ddns.net'
  username: 'postgres'
  password: '140496'
env:
  no-reply-email: no-reply@${ssm:/connect/${self:stage}/email/domain}
